definitions:
  github_com_leandroag_desafio_app_dtos.CreateAccountDTO:
    properties:
      balance:
        type: number
      cpf:
        type: string
      name:
        type: string
      secret:
        type: string
    type: object
  github_com_leandroag_desafio_app_dtos.ListAccountDTO:
    properties:
      balance:
        type: number
      cpf:
        type: string
      name:
        type: string
    type: object
  github_com_leandroag_desafio_app_dtos.TransferDTO:
    properties:
      account_destination_id:
        type: integer
      account_origin_id:
        type: integer
      amount:
        type: number
    type: object
info:
  contact: {}
  description: Credit Card Billing REST API.
  license:
    name: Stone Co®
  title: Credit Card Billing
  version: 0.0.1
paths:
  /api/http/v1/account:
    get:
      consumes:
      - application/json
      description: Returns a list of accounts.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_leandroag_desafio_app_dtos.ListAccountDTO'
            type: array
        "500":
          description: Error getting accounts
          schema:
            type: string
      summary: List accounts
      tags:
      - Account
    post:
      consumes:
      - application/json
      description: Creates a new account.
      parameters:
      - description: Account object
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/github_com_leandroag_desafio_app_dtos.CreateAccountDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Account created successfully
          schema:
            type: string
        "400":
          description: Invalid request payload
          schema:
            type: string
        "500":
          description: Error creating account
          schema:
            type: string
      summary: Create account
      tags:
      - Account
  /api/http/v1/transfers:
    get:
      description: Retrieves a list of transfers made by the authenticated account
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_leandroag_desafio_app_dtos.TransferDTO'
            type: array
        "400":
          description: Invalid request payload
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Retrieves a list of transfers
      tags:
      - transfers
schemes:
- https
swagger: "2.0"
